version: '3.7'

services:
    server:
        build:
            context: ./tc-be
            dockerfile: Dockerfile
        image: doger-server
        container_name: doger-node-server
        command: /usr/src/app/node_modules/.bin/nodemon index.js
        volumes:
            - ./tc-be/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '5000:5000'
        depends_on:
            - mongo
        # env_file: ./server/.env
        environment:
            - NODE_ENV=development
        networks:
            - app-network
    mongo:
        image: mongo
        volumes:
            - data-volume:/data/db
        ports:
            - '27017:27017'
        networks:
            - app-network
    client:
        build:
            context: ./tc-fe
            dockerfile: Dockerfile
        image: doger-client
        container_name: doger-react-client
        command: npm start
        volumes:
            - ./tc-fe/:/usr/app
            - /usr/app/node_modules
        depends_on:
            - server
        ports:
            - '3000:3000'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local
