service: doger-app
plugins:
    - serverless-express
provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: us-east-1
    memorySize: 128
functions:
    app:
        handler: index.handler
        events:
            - http:
                  method: GET
                  path: /test
